apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: ${name}
spec:
  acme:
    email: ${email}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: ${private_key_secret}
    solvers:
    - dns01:
        route53:
          region: ${aws_region}
          hostedZoneID: ${hosted_zone_id}
